version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npx lerna run test

workflows:
  main:
    jobs:
      - test

executors:
  node:
    docker:
      - image: cimg/node:lts

# VS Code Extension Version: 1.0.0