version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
              - node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - node-cache-v1-{{ .Branch }}-
              - node-cache-v1-
      - run:
          name: Fetch dependencies
          command: npm install
      - save_cache:
          key: node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
              - ~/.npm  
              - ~/.cache
              - ~/node_modules
      - run: npx lerna run test 

workflows:
  main:
    jobs:
      - test

executors:
  node:
    docker:
      - image: cimg/node:lts

# VS Code Extension Version: 1.0.0